### ISSUE TITLE
EmailShareButton cannot open email in new window

### ISSUE THREAD

**Issue by zozoens31** [nygardk/react-share#153]
Clicking on EmailShareButton removes the current page and replace it with Gmail (if that's what is set as the user's mail manager in browser).

It would be nice to have the possibility to open it in a new page.

**Comment by hiradyazdan** [comment]
you can override the default prop of `openWindow` to `true`. By default it is set to `false`.

**Comment by pcorpet** [comment]
Note that in v4, `openWindow` param got renamed to `openShareDialogOnClick`

**Comment by krishom** [comment]
Setting `openShareDialogOnClick` does open the mailto in a popup, but the original page also handles the mailto so I end up with the same Gmail message in both windows.

**Comment by perryjsteward** [comment]
> Setting `openShareDialogOnClick` does open the mailto in a popup, but the original page also handles the mailto so I end up with the same Gmail message in both windows.

I'm experiencing the same issue as this, has there been a fix deployed at all?

**Comment by cassiocardoso** [comment]
For those still having this issue, you can pass an empty `onClick` callback to the component to prevent the page from loading the Gmail window:

```js
<EmailShareButton
    onClick={() => {}}
    openShareDialogOnClick
    url={url}
>
	...
</EmailShareButton>
```

**Comment by coding404life** [comment]
> For those still having this issue, you can pass an empty `onClick` callback to the component to prevent the page from loading the Gmail window:
> 
> ```js
> <EmailShareButton
>     onClick={() => {}}
>     openShareDialogOnClick
>     url={url}
> >
> 	...
> </EmailShareButton>
> ```

thanks so much your a life savior
