### ISSUE TITLE
Type errors after migrating to v4

### ISSUE THREAD

**Issue by andreiho** [nygardk/react-share#277]
I migrate to v4 and I'm now getting these type errors:

```
Type '{ children: Element; url: string; }' is missing the following properties from type 'Pick<Props<{ quote?: string; hashtag?: string; }>, "form" | "style" | "title" | "type" | "name" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 264 more ... | "resetButtonStyle">': form, title, type, name, and 256 more.
```

I'm using it like this, nothing special:

```
<FacebookShareButton url={url}>
  <FacebookIcon {...iconProps} />
</FacebookShareButton>
```

It seems to require all props including native ones. I checked out the demo and it works as expected. I'm on the latest react and typescript versions.

Any ideas? @nygardk

**Comment by eshton** [comment]
I have the same issue, please help!

**Comment by eshton** [comment]
Found a workaround until: https://medium.com/@tomsoir/typescript-how-to-rewrite-type-definition-file-file-d-ts-of-any-node-modules-package-1eed7f5630d1

`declare module 'react-share' {
  declare const FacebookShareButton: any;
  declare const FacebookIcon: any;
  declare const TwitterIcon: any;
  declare const TwitterShareButton: any;

  export {
    FacebookShareButton,
    TwitterShareButton,
    FacebookIcon,
    TwitterIcon
  }
}`

**Comment by scroobius-pip** [comment]
@nygardk any updates please ?

**Comment by knpwrs** [comment]
My workaround is currently the following:

```tsx
{/*
// @ts-ignore: https://github.com/nygardk/react-share/issues/277 */}
<FacebookShareButton {...shareProps}>
  <FacebookIcon size={24} />
</FacebookShareButton>
```

Far from ideal, though it's basically the same as redeclaring an export as `any`.

**Comment by andreiho** [comment]
After another round of upgrading all my dependencies, the issue seems to be gone. I'm on TypeScript 3.8.2 now. Not sure where and why exactly it went wrong.

**Comment by tomdracz** [comment]
For me, this one was solved by install/update of `@types/react` package. I had it at 16.9.5 and 16.9.35 silenced the warnings. Might possibly also fix #301

**Comment by KarandikarMihir** [comment]
I upgraded react types and it seemed to do the trick. `"@types/react": "16.9.35"`

**Comment by dewaleolaoye** [comment]
Yeah, `@types/react` upgrade fix it on my end too

**Comment by nygardk** [comment]
I hope it's fixed with having the newest version of `@types/react`. Please open a new issue if not 🙂 .

**Comment by knpwrs** [comment]
I'm still seeing this on `react-share@^4.2.0`, `@types/react@^16.9.35`, and `typescript@^3.9.5`. @nygardk would you prefer a new issue or can we re-open this one?

**Comment by exinferis** [comment]
Same problem occurs or me as well with `typescript@^3.9.5`, `@types/react@^16.9.37` and `react-share@^4.2.0`

Ignoring it for now using `{/*// @ts-ignore: https://github.com/nygardk/react-share/issues/277 */}` seems to be the best option I could find.

**Comment by definitelyreal** [comment]
I believe the issue is here: https://github.com/nygardk/react-share/blob/e72dba51654c8277b9cfd87b9e8f354b36017fd3/src/hocs/createIcon.tsx#L3

The Props required by Icon inherit all SVGProps. I think this would be a simple fix of changing `Omit<React.SVGProps<SVGSVGElement>, 'width' | 'height'>` to `Omit<Partial<React.SVGProps<SVGSVGElement>>, 'width' | 'height'>`

**Comment by danielholmes** [comment]
I was able to fix my issue by changing `children` and `url` to optional in the `CustomProps` interface in `ShareButton.d.ts` (in my case I applied it using [patch-package](https://github.com/ds300/patch-package))

**Comment by shaohaolin** [comment]
+1 for this issue.

**Comment by shi-rudo** [comment]
also +1

**Comment by shaohaolin** [comment]
Can't build even the project doesn't import the counter.

````
 ERROR in D:/Repo/EsportsHub/services/EsportsHub/src/Service/node_modules/react-share/lib/VKShareCount.d.ts
 ERROR in D:/Repo/EsportsHub/services/EsportsHub/src/Service/node_modules/react-share/lib/VKShareCount.d.ts(17,8):
 TS2344: Type '"hidden" | "color" | "style" | "title" | "children" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | "className" | ... 243 more ... | "translate"' does not satisfy the constraint '"hidden" | "color" | "style" | "title" | "children" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | "className" | ... 243 more ... | "getCount"'.
      Type '"translate"' is not assignable to type '"hidden" | "color" | "style" | "title" | "children" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | "className" | ... 243 more ... | "getCount"'.

**Comment by christopher-caldwell** [comment]
Would you prefer a "+1" comment, or just thumbing up the 1st comment?
